# fly.toml app configuration file generated for lis-pocketbase on 2025-08-15T00:01:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lis-pocketbase'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    method = 'GET'
    path = '/api/health'
    protocol = 'http'
    timeout = '10s'
    interval = '30s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'pb_data'
  destination = '/pb/pb_data'
